env_type: ['realistic_fake']
max_epoch_steps: [25]
learning_rate: [0.001]
gamma: [0.9]
total_timesteps: 1000000
name_space: 'realistic_fake_with_error'
# verbose: 1
# model_save_freq: 10000
noise_sigma: [0.1]
# train_freq: 
#     step: [1]
# stop_on_success: False