env_type: ['realistic_fake']
max_epoch_steps: [25]
learning_rate: [0.01]
gamma: [0.9]
total_timesteps: 1000000
name_space: 'realistic_fake_boh'
verbose: 1
model_save_freq: 1000000
noise_sigma: [0.1]
train_freq: 
    episode: [1,2,3,4]