# env_type: ['realistic_fake_param_pos_and_reward','realistic_fake_param_pos_and_reward_history','realistic_fake_param_and_pos']
env_type: ['realistic_fake_param_pos']
max_epoch_steps: [25]
learning_rate: [0.01]
gamma: [0.9]
total_timesteps: 1000000
model_types: ['td3']
name_space: 'boh_2'
verbose: 1
history_len: [10]
# model_save_freq: 2500000