env_type: ['force_pag_in_hole']
max_epoch_steps: [25,50]
learning_rate: [0.001,0.0001]
gamma: [0.9]
total_timesteps: 100000
name_space: 'force_pag_in_hole_2'
# verbose: 1
# model_save_freq: 5000
noise_sigma: [0.1]
# train_freq: 
#     step: [1]
stop_on_success: False