 env_type: 'fake'
 max_epoch_steps: [15,20]
 learning_rate: [0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01]
 gamma: [0.9]
 total_timesteps: 100000
 model_types: ['td3']
 name_space: 'last_fake_tests_'
 verbose: 0