 env_type: 'random_real_fake'
 max_epoch_steps: [25,30,40,50,100]
 learning_rate: [0.01]
 gamma: [0.9]
 total_timesteps: 1000000
 model_types: ['td3']
 name_space: 'rand_real_fake_1'
 verbose: 1
 model_save_freq: 100000