 env_type: 'fake'
 max_epoch_steps: [10,15,20,30,40,50]
 learning_rate: [0.01]
 gamma: [0.5,0.6,0.7,0.8,0.9,0.99]
 total_timesteps: 100000
 model_types: ['td3']
 name_space: 'casual_test_'
 verbose: 0