 env_type: 'realistic_fake'
 max_epoch_steps: [25,30,35,40]
 learning_rate: [0.01]
 gamma: [0.9]
 total_timesteps: 200000
 model_types: ['td3']
 name_space: 'realistic_tests_'
 verbose: 1
 model_save_freq: 10000