max_epoch_steps: [50,100,200]
learning_rate: [0.001]
gamma: [0.9]
total_timesteps: 2000000
name_space: 'general_diff'
verbose: 0
# model_save_freq: 1000000
noise_sigma: [0.1]
space_dimension: [6]    
history_len: [10,20]
single_threshold: [0.01,0.001]
use_reward: [True,False]