learn_params: # In this file we define the bounds for every parameter. Write only the parameters to be modified
  actions:
    can_peg_in_hole:
      skills:
        move_to_can_grasp:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]

        move_to_hole_insertion:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]
    container1_peg_in_hole:
      skills:
        move_to_container1_grasp:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]

        move_to_container1_insertion:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]
    item_peg_in_hole:
      skills:
        move_to_item_grasp:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]

        move_to_item_insertion:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]
    container2_peg_in_hole:
      skills:
        move_to_container2_grasp:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]

        move_to_container2_insertion:
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]


