learn_params: # In this file we define the bounds for every parameter. Write only the parameters to be modified
  actions:
    can_peg_in_hole:
      skills:
        move_to_can_grasp:
          acceleration_scaling: [0,1]
          velocity_scaling: [0,1]
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]

        move_to_hole_insertion:
          acceleration_scaling: [0,1]
          velocity_scaling: [0,1]
          relative_position: 
            - [-0.05, 0.05]
            - [-0.05, 0.05]
            - [-0.05, 0.05]

        insert:
          goal_twist: 
            - [0,0.01]
            - [0,0.01]
            - [0.01,0.1]
            - [0,0]
            - [0,0]
            - [0,0]
          target_force: [10,600]
