# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  panda_joint1:
    min_position: -2.9671
    max_position:  2.9671
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  panda_joint2:
    min_position: -1.8326
    max_position:  1.8326
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  panda_joint3:
    min_position: -2.9671
    max_position:  2.9671
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  panda_joint4:
    min_position: -3.1416
    max_position:  0.0873
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  panda_joint5:
    min_position: -2.9671
    max_position:  2.9671
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  panda_joint6:
    min_position: -0.0873
    max_position:  3.8223
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  panda_joint7:
    min_position: -2.9671
    max_position:  2.9671
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0